### ISSUE TITLE
file: add character dialogue files

### ISSUE THREAD

**Issue by NewYorkKim** [DevTillDie/ForestTori#1]
## ✏️ Summary
식물 대사 CSV 파일 추가

<br>

## ✨ Description
서비스 진행에 필요한 식물 캐릭터별 대사 CSV 파일을 프로젝트에 추가합니다.
(식물 캐릭터는 MVP에 해당하는 4종으로 한정)

<br>

## ✓ Todo
- [x] 구글 드라이브에 CSV 파일 생성
- [x] CSV 파일 다운로드
- [x] 프로젝트에 CSV 파일 추가
