### ISSUE TITLE
fix : fix ui

### ISSUE THREAD

**Issue by NewYorkKim** [DevTillDie/ForestTori#113]
## ✏️ Summary
UI 수정

<br>

## ✨ Description
세미QA 결과, 수정이 필요한 UI 부분들을 수정합니다.

<br>

## ✓ Todo
- [x] 온보딩 버튼 stroke 수정
- [x] 메인 대사 패딩 수정
- [x] 메인 오브젝트 너비, 높이 고정
- [x] transition 효과 추가
- [x] 정원 안내 문구 타이밍 수정

<br>
