### ISSUE TITLE
fix : fix view errors

### ISSUE THREAD

**Issue by NewYorkKim** [DevTillDie/ForestTori#125]
## ✏️ Summary
뷰 오류 수정

<br>

## ✨ Description
뷰와 관련된 오류를 수정합니다.

<br>

## ✓ Todo
- [x] 온보딩 이름 세팅 뷰
- [x] 챕터 완료 팝업 뷰 - 함수
- [x] 미션 완료 이후 메인 뷰
