### ISSUE TITLE
feat : set initial data in DataManger

### ISSUE THREAD

**Issue by yoohyebin** [DevTillDie/ForestTori#35]
## ✏️ Summary
- DataManger에서 초기 데이터 세팅

<br>

## ✨ Description
- tsv 파일 형태로 식물에 대한 데이터를 읽어와 초기 데이터를 세팅
- 식물들을 각각 챕터에 맞게 세팅

<br>

## ✓ Todo
- [ ] Plant 모델 구조 수정
- [ ] tsv 파일 생성
- [ ] 초기 데이터 세팅
<br>
