### ISSUE TITLE
feat: integrate main view and garden view

### ISSUE THREAD

**Issue by NewYorkKim** [DevTillDie/ForestTori#45]
## ✏️ Summary
메인 뷰 - 정원 뷰 통합

<br>

## ✨ Description
메인 뷰와 정원 뷰를 통합합니다.

<br>

## ✓ Todo
- [x] 메인 뷰 - 정원 뷰 화면 연결
- [x] Plant 모델 수정
- [x] 정원 오브젝트 업데이트 로직 추가
- [x] 화면 레이아웃 수정
