### ISSUE TITLE
design : modify history view ui

### ISSUE THREAD

**Issue by NewYorkKim** [DevTillDie/ForestTori#93]
## ✏️ Summary
성장일지 관련 뷰 UI 수정

<br>

## ✨ Description
성장일지 관련 뷰 UI를 수정합니다.

<br>

## ✓ Todo
- [x] 성장일지 작성 UI 수정
- [x] 성장일지 작성 UI keyboard handler 재적용
- [x] 성장일지 히스토리 UI 수정
